spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE} #job.name값이 없으면 NONE을 할당, NONE이 할당되면 어떤 배치도 실행하지 않겠다는 의미

---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

---
spring:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/batchdb
      username: batch_user
      password: batch_user
      driver-class-name: com.mysql.jdbc.Driver